### ISSUE TITLE
Assignment 3 is ready for grading!

### ISSUE THREAD

**Issue by melmlr** [SES-5215-F2020/melmiller-quant#4]
Hi - Assignment 3 is now ready for grading. The .RMD file can be found [here](https://github.com/SES-5215-F2020/melmiller-quant/blob/master/Assignment%203_FINAL.Rmd), and the .HTML file can be found [here](https://ses-5215-f2020.github.io/melmiller-quant/Assignment-3_FINAL).

I look forward to your feedback -- and to continue working with this data!

Best,
Mel

**Comment by saratepfer** [comment]
Really nice job on this, Mel! A few comments below:

- For your first box plot (housing tenure and age), I wouldn't rotate the axis labels, since they're not all that long to begin with. They should be fine oriented perpendicular to the tick marks.
- Same for the second box plot (housing tenure and total income)
- It's not required for the assignment, but it would be great to see some ideas for visualizing the results of a chi squared test.
